rwjblue/codemod-cli

- commands/local/test.js
Test command allows all jest cli flags to be passed through.  But it is
important to document via our `--help` output at least the basics to
elude to new users that it is available.
> Add commont jest arguments to test command

- commands/global/new.js
- commands/local/test.js
- package.json
- yarn.lock
In the future we will be shipping codemod-cli as a dependency of the project (so that it can defer to codemod-cli from its bin script).
This change is a simple precursor that allows `jest` to _not_ be a "production dependency" of either codemod-cli or the project itself.
> Move jest to project dependency.

- src/test-support.js
- tests/cli-test.js
This change unlocks testing of transforms which depends on a location of a file to be transformed. 
Currently with `runInlineTest` transforms only have access to the file `source` while transforms launched via jscodeshift [receive](https://github.com/facebook/jscodeshift/blob/595b15cda4f52673cad8fe3ae65c12e334966dbf/src/Worker.js#L131) both `source` and `path` options. So this change makes `runInlineTest` test helper behave more similar to jscodeshift.
----
Thanks a lot for the codemod-cli! it encouraged me to start writing my first codemod :smile:
> Pass a file path to the runInlineTest

- tests/cli-test.js
Apparently, jscodeshift runs the provided path through `fs.realpathSync` but the return value from `broccoli-test-helper` hasn't passed through `realpathSync`.
On most linux / windows systems this doesn't matter, but on mac the `$TMPDIR` is references as `/var/folders/random-stuff/here/` but "really" is at `/private/var/folders/random-stuff/here/`.
> Ensure to use real path for `file.path` expectation.

- tests/cli-test.js
This PR adds two new tests for class and decorator syntax, including with TypeScript.
> Add two tests for experimental class/decorators

- commands/global/new.js
This is a fix for https://github.com/facebook/jest/issues/6766, which a fresh `codemod-cli` project also suffered from. (see https://github.com/facebook/jest/issues/6766#issuecomment-408381957)
> Add jest testEnvironment to package.json

- src/test-support.js
- tests/cli-test.js
Use globby to include tests from subfolders in the `__testfixtures__`
> Update transform to include subfolders from the testfixtures in the test run

- src/bin-support.js
In some circumstances the `jscodeshift` binary is not found by `execa` (e.g. when using `npx`). This changes things around to manually resolve the binary path and use it directly.
Fixes https://github.com/rwjblue/ember-qunit-codemod/issues/140.
> Resolve jscodeshift binary path manually.

- commands/local/update-docs.js
Was caused by a missing `S`
I fixed the typo and updated the regex to cater for people that already run this command
> fix update-docs no refresh content after first run

- src/test-support.js
This makes it possible to write codemods with TypeScript using a `.ts` extension with `ts-jest`.
> Do not assume transform files are `.js`

- commands/global/new.js
- package.json
- yarn.lock
Fixes #58
1. Adding coveralls to the global new command
2. Adding coveralls as a dev dependency
3. Tweaking test script to run coverage
> [FEAT] Adding coverage statistics collection with coveralls

- src/test-support.js
- tests/cli-test.js
This change will make writing accurate tests much easier. Possibly breaking.
> Removes `input` suffix from the path indicated during a test

- src/bin-support.js
We can reduce the number of files sent to jscodeshift by filtering the paths with the `extensions` option.
Thus, we clean up the codemod's stack trace from an error shown on the screenshot:
> bin-support: Filter paths with extensions

- README.md
> [DOCS] Add debugging workflow info docs

- commands/global/new.js
- commands/local/generate/codemod.js
We recently had an engineer who was not familiar with npx and could not figure out
how to run a new codemod locally.
I've updated the blueprint to make it clear to new users how to run a codemod locally before
publishing.
> [docs] Update the readme blueprint for local usage

- .github/workflows/ci.yml
- bin/cli.js
- package.json
- tests/cli-test.js
Supercedes #76 
@rwjblue I was able to figure out what was causing `yarn` to fail in tests. In a spike I added `{ stdio: 'inherit' }` to the `execa` call to show the output of running `yarn`, which showed that apparently the previously symlinked node_modules folders were causing some trouble. See the [CI log output](https://github.com/simonihmig/codemod-cli/runs/765295324?check_suite_focus=true#step:5:29).
This PR takes your previous commit, and adds one to change the order of running `yarn` before symlinking.
> Drop node 8

- commands/local/generate/codemod.js
- commands/local/generate/fixture.js
- package.json
- src/bin-support.js
- src/test-support.js
- src/test-support/jscodeshift.js
- src/test-support/template.js
- src/test-support/utils.js
- src/transform-support.js
- tests/cli-test.js
- yarn.lock
> Add support for template codemods

- src/bin-support.js
- src/options-support.js
- tests/cli-test.js
> Added support for accepting `jscodeshift` ignore options (e.g. `--ignore-config` and `--ignore-pattern`)

- commands/global/new.js
* Remove Node 8 testing (already didn't support it, just missed this reference)
* Remove `npm i -g yarn` (installed by default)
* Add `--frozen-lockfile` on test runs that should always use the lockfile
> Fixup GH Actions configuration for new projects.

- commands/global/new.js
- tests/cli-test.js
IMHO, this is non-breaking as it is only about _new_ projects that are generated, not existing ones.
> Remove .travis.yml from newly generated projects.

- commands/local/update-docs.js
- tests/cli-test.js
- This is needed when working on transforms that require different i/o file types. Addresses https://github.com/rwjblue/codemod-cli/issues/120
- The regex is used to only process files with 'input.' or 'output.' in their filename. For some reason lookbehind groups are deemed invalid by eslint, which should be supported in these v
ersions of node, but I wasn't able to get eslint to accept it. It would provide an additional layer of accuracy by ensuring a '.input.' pattern, but I feel confident that the lookahead is
safe to use given the relatively structured nature of fixture filenames.
> Updated `update-docs` command to respect mixed file type extensions

- src/options-support.js
@rwjblue I noticed that `--run-in-band` wasn't being passed to jscodeshift when running codemods via the codemod-cli. I've gotten around this by hardcoding the value locally, but seems that this (and a few other) jscodeshift args should be respected by default.
> Added some more default options for jscodeshift command line args

- src/bin-support.js
Fix [issue 155](https://github.com/rwjblue/codemod-cli/issues/155). Change the bin entry for `ember-template-recast` for better compatibility.
```shell
✨  Done in 69.59s.
```
> fix the break when running ember-template-recast

- commands/local/generate/codemod.js
- commands/local/generate/fixture.js
- src/bin-support.js
- src/test-support.js
- src/test-support/utils.js
- src/transform-support.js
- tests/cli-test.js
- Add `--codemod-dir` command line flag to `codemod-cli generate`
- Add support for custom paths in `runTransformTest` (add `path` option)
- Allow `runTransform` to accept path to transform to run
- Allow specifying a custom fixture directory
> Allow alternate folder structures for codemod-cli project

- package.json
- yarn.lock
https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ 
Since the `colors@1.4.1` was broken, `jscodeshift` decided to use `chalk` instead of `colors`. https://github.com/facebook/jscodeshift/pull/473
Let's upgrade the `jscodeshift` to the latest version to avoid using the broken `colors` library.
> Upgrade jscodeshift to avoid using the broken colors library

- src/bin-support.js
jscodeshift allows for file lists to be supplied via stdin, which is useful when the list of files is long enough that the max length for a command is exceeded. For projects with large numbers of files to codemod this limit is easy to hit.
This PR shifts codemod-cli to take the list of files obtained from `globby`, converts them into a `Readable` stream, and then pipes that tream to the execa process's stdin for jscodeshift to use.
See https://github.com/ember-codemods/es5-getter-ember-codemod/issues/34 for example failure
> fix: supply file list to jscodeshift via stdin
